#!/usr/bin/env bash
#
# setup-stack-manager-aliases.sh
#
# Sets up convenient aliases and bash completion for stack-manager.sh
#
# Usage:
#   ./scripts/setup-stack-manager-aliases.sh
#   source ~/.bashrc  # Or restart terminal
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "Setting up Stack Manager aliases..."
echo

# Detect shell
SHELL_RC=""
if [[ -n "${BASH_VERSION:-}" ]]; then
    SHELL_RC="$HOME/.bashrc"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
    SHELL_RC="$HOME/.zshrc"
else
    echo "Unsupported shell. Please add aliases manually."
    exit 1
fi

echo "Detected shell config: $SHELL_RC"
echo

# Check if already added
if grep -q "# Stack Manager Aliases" "$SHELL_RC" 2>/dev/null; then
    echo "Aliases already added to $SHELL_RC"
    read -p "Do you want to update them? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping..."
        exit 0
    fi

    # Remove old section
    sed -i '/# Stack Manager Aliases/,/# End Stack Manager Aliases/d' "$SHELL_RC"
fi

# Add aliases
cat >> "$SHELL_RC" << EOF

# ============================================================
# Stack Manager Aliases
# Generated by setup-stack-manager-aliases.sh
# ============================================================

# Project root
export DPG_ROOT="$PROJECT_ROOT"

# Stack manager shortcuts
alias sm='\$DPG_ROOT/scripts/stack-manager.sh'
alias sm-start='\$DPG_ROOT/scripts/stack-manager.sh start'
alias sm-stop='\$DPG_ROOT/scripts/stack-manager.sh stop'
alias sm-restart='\$DPG_ROOT/scripts/stack-manager.sh restart'
alias sm-status='\$DPG_ROOT/scripts/stack-manager.sh status'
alias sm-logs='\$DPG_ROOT/scripts/stack-manager.sh logs'
alias sm-clean='\$DPG_ROOT/scripts/stack-manager.sh clean'
alias sm-interactive='\$DPG_ROOT/scripts/stack-manager.sh interactive'
alias sm-menu='\$DPG_ROOT/scripts/stack-manager.sh interactive'

# Quick stack starters
alias sm-dev='\$DPG_ROOT/scripts/stack-manager.sh start dev --tools'
alias sm-citus='\$DPG_ROOT/scripts/stack-manager.sh start citus'
alias sm-patroni='\$DPG_ROOT/scripts/stack-manager.sh start patroni'
alias sm-monitoring='\$DPG_ROOT/scripts/stack-manager.sh start monitoring'
alias sm-prod='\$DPG_ROOT/scripts/stack-manager.sh start production'

# Database connections
alias psql-dev='psql "postgresql://dpg_cluster:dpg_cluster_2026@localhost:5432/distributed_postgres_cluster"'
alias psql-citus='psql "postgresql://dpg_cluster:dpg_cluster_2026@localhost:5432/distributed_postgres_cluster"'
alias psql-patroni='psql "postgresql://postgres:postgres@localhost:5000/postgres"'
alias psql-prod='psql "postgresql://postgres@localhost:5432/distributed_postgres_cluster"'

# Monitoring shortcuts
alias open-grafana='open http://localhost:3000 2>/dev/null || xdg-open http://localhost:3000 2>/dev/null || echo "Open http://localhost:3000 in your browser"'
alias open-prometheus='open http://localhost:9090 2>/dev/null || xdg-open http://localhost:9090 2>/dev/null || echo "Open http://localhost:9090 in your browser"'
alias open-pgadmin='open http://localhost:8080 2>/dev/null || xdg-open http://localhost:8080 2>/dev/null || echo "Open http://localhost:8080 in your browser"'
alias open-haproxy='open http://localhost:7000 2>/dev/null || xdg-open http://localhost:7000 2>/dev/null || echo "Open http://localhost:7000 in your browser"'

# Docker shortcuts for DPG
alias dpg-ps='docker ps --filter "name=dpg-*" --filter "name=citus-*" --filter "name=patroni-*"'
alias dpg-logs='docker logs -f'
alias dpg-stats='docker stats \$(docker ps -q --filter "name=dpg-*" --filter "name=citus-*" --filter "name=patroni-*")'

# Helper functions
dpg-exec() {
    if [[ \$# -lt 2 ]]; then
        echo "Usage: dpg-exec <container-name> <command>"
        return 1
    fi
    docker exec -it "\$1" "\${@:2}"
}

dpg-psql() {
    local container="\${1:-dpg-postgres-dev}"
    docker exec -it "\$container" psql -U dpg_cluster -d distributed_postgres_cluster
}

dpg-redis() {
    local container="\${1:-dpg-redis-dev}"
    docker exec -it "\$container" redis-cli
}

# Bash completion
if [[ -f "\$DPG_ROOT/scripts/stack-manager-completion.bash" ]]; then
    source "\$DPG_ROOT/scripts/stack-manager-completion.bash"
fi

# End Stack Manager Aliases
# ============================================================

EOF

echo "✓ Aliases added to $SHELL_RC"
echo
echo "Available aliases:"
echo
echo "  Stack Manager:"
echo "    sm                  - Stack manager command"
echo "    sm-start <mode>     - Start a stack"
echo "    sm-stop <mode>      - Stop a stack"
echo "    sm-status           - Show all stacks status"
echo "    sm-logs <mode>      - View logs"
echo "    sm-interactive      - Interactive menu"
echo
echo "  Quick Starters:"
echo "    sm-dev              - Start dev stack with PgAdmin"
echo "    sm-citus            - Start Citus cluster"
echo "    sm-patroni          - Start Patroni HA cluster"
echo "    sm-monitoring       - Start monitoring stack"
echo
echo "  Database Access:"
echo "    psql-dev            - Connect to dev PostgreSQL"
echo "    psql-citus          - Connect to Citus coordinator"
echo "    psql-patroni        - Connect to Patroni primary"
echo
echo "  Monitoring:"
echo "    open-grafana        - Open Grafana dashboard"
echo "    open-prometheus     - Open Prometheus"
echo "    open-pgadmin        - Open PgAdmin"
echo "    open-haproxy        - Open HAProxy stats"
echo
echo "  Docker Helpers:"
echo "    dpg-ps              - Show DPG containers"
echo "    dpg-logs <name>     - Follow container logs"
echo "    dpg-stats           - Show container resource usage"
echo "    dpg-exec <name> <cmd>  - Execute command in container"
echo "    dpg-psql [name]     - Connect to PostgreSQL container"
echo "    dpg-redis [name]    - Connect to Redis container"
echo
echo "To activate aliases, run:"
echo "  source $SHELL_RC"
echo
echo "Or restart your terminal."
